### ISSUE TITLE
Module Roll Support: Better Rolls for 5e

### ISSUE THREAD

**Issue by MrBrentRogers** [caoranach/DiscordConnect#10]
You mentioned rolls not working for Midi-QOL but also for "Better Rolls for 5e" does not send rolls (gives all rolls are "0")

**Comment by caoranach** [comment]
I'll have to take a look! I unfortunately have been super busy lately and havent had much time to work on it. This won't be in v1.0.5, but hopefully I'll be able to look into it for v1.0.6!

**Comment by MrBrentRogers** [comment]
With Better Rolls for 5e not supported with FoundryVTT v10 I'm closing this issue
