### ISSUE TITLE
Module Settings Information

### ISSUE THREAD

**Issue by MrBrentRogers** [caoranach/DiscordConnect#11]
### Setup
1. Create a Webhook in your Discord server, and specify which channel to output chat to. Copy the Webhook URL, you'll need it later.
 a. Server Settings (or channel settings) > Integrations > Webhooks > [New Webhook]
 b. Set webhook name and channel to post to.
 c. [Copy Webhook URL]

_Note_: if you're planning on having different Foundry Worlds post to separate Discord OR a separate channel for Rolls, additional Webhooks will need to be created.

2. Add the module to FoundryVTT using FoundyVTT "Install Module" in setup

3. Open the Foundry world > Enable the DiscordConnect Module

4. Configure the module settings.
 **Main GM ID**: [[See below]]

 **Ignore Whispers & Private Rolls**: Check to ensure GM and Private Rolls (chat) aren't posted to Discord for all to see.

 **Game Invite URL**: the external, internet URL everyone connects to the server through
 Game Settings > Game Access > Invitation Links "Internet"

**Webhook URL:** Discord Webhook URL from Step 1.

**Roll Webhook URL**: Discord Webhook URL for rolls - either the same webhook for rolls to appear in the same channel as chat, or a separate webhook needs to be setup for for the rolls to appear in. Leave empty to ignore all rolls.

### Getting Main GM ID
1. Open browser Inspect/Developer Tools on the Foundry tab
Chrome: (Windows, Linux, Chrome OS): [F12] or Control+Shift+C
Chrome (Mac): Command+Option+C

2. Within Console type:
`game.user` for current user information
`game.users` for all user information

3. Expand to find the correct user's name and find the _id (> data : 16 character string)
This is the ID needed for the Main GM ID field. 

**_NOTE_**:  Main GM must be logged in for DiscordConnect to work

**Comment by caoranach** [comment]
Thanks! I incorporated this into 1.0.5's README. You did a much better job of explaining it than I did!
