### ISSUE TITLE
Only send Public Rolls & unable to install via json

### ISSUE THREAD

**Issue by DrWiFi** [caoranach/DiscordConnect#2]
First off, I think this is a great idea, when it works with Midi-Qol and Better Rolls I will definitely have it active.
I ran into a couple of issues though:

1. I get an error that the json is invalid when trying to install via the json link.
2. There should be a way to ignore anything other than public rolls, that way private rolls are not broadcast to the users.
Thanks
~DrWiFi

**Comment by caoranach** [comment]
Thanks for trying it out! I realized the json issue, but I havent had the time to fix yet. I'll hopefully have it fixed later today. I definitely want to provide more options for privacy, etc!

**Comment by caoranach** [comment]
This issue is fixed, and will be in the release of 1.0.2 today!
