### ISSUE TITLE
Option to ignore rolls completely (at least until midi-qol / better rolls is supported)

### ISSUE THREAD

**Issue by DrWiFi** [caoranach/DiscordConnect#7]
Hello,
You have made great strides with this. I love the option to put rolls into a different channel. I was initially not going to enable this yet because the channel would fill with rolls of 0. 
Right now I am making a dummy channel for the roll webhook, but it seems more intuitive (at least to me) to not send the rolls if the field is blank.
Thanks for making something I didn't even realize was needed until I saw it. :)

**Comment by caoranach** [comment]
I can't believe I didn't think to do this from the beginning! Now its a thing ;)

Thanks for thinking of it!
