### ISSUE TITLE
Big descriptions of attack/spell go here!

### ISSUE THREAD

**Issue by bklick** [caoranach/DiscordConnect#9]
Cool mod! Glad I found it. Small issue:

![image](https://user-images.githubusercontent.com/3947702/111056930-f94cbe00-8448-11eb-853a-dceb1893c816.png)

No matter what a spell description says, discord outputs this text. Is there a place I can go to change that?

**Comment by AdmiralBenguin** [comment]
currently DiscordConnect does not have the ability to parse HTML content. Do keep an eye out for when that functionality might be added in the future, the mod author is aware of it!

**Comment by caoranach** [comment]
For now, I've simply suppressed the messages. They'll no longer be sent to discord for the moment! I still hope to provide some support for such messages in the future.
